name: c1
env: push
 apps_name: my-app
jobs:
  runs-on: ubuntu-latest
  env:
    Node_env: production
  steps:
    - name: show them
    env:
    greeting: ello
    run: echo "$app_name $node_env $greeting"
