name: c1

on: push

env:
  app_name: my-app

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - name: Show them
        env:
          greeting: hello
        run: echo "$app_name $NODE_ENV $greeting"
